<?php
/** NoAd 去广告系统 v4 配置文件 */

return array(
    'noad_enabled' => false,
    'debug_mode' => false,
    'enable_ad_filter' => false,
    'enable_ts_proxy' => true,
    'ad_keyword_threshold' => 2,
    'cache_enabled' => false,
    'cache_ttl' => 1800,
    'cache_dir' => __DIR__ . '/../cache',
    'enable_multi_source' => false,
    'max_source_try' => 3,
    'request_timeout' => 10,
    'ad_keywords' => array (
  0 => 'ad',
  1 => 'ads',
  2 => 'advert',
  3 => 'advertisement',
  4 => 'pre-roll',
  5 => 'mid-roll',
  6 => 'post-roll',
  7 => 'adbreak',
  8 => 'adslot',
  9 => 'adzone',
  10 => 'adbreak',
  11 => 'sponsor',
  12 => '广告',
  13 => '插播',
  14 => '片头广告',
  15 => '片中广告',
  16 => '片尾广告',
  17 => '推广',
  18 => '推广位',
  19 => '商业广告',
  20 => '贴片广告',
  21 => '暂停广告',
  22 => '角标广告',
  23 => '浮动广告',
  24 => '前置广告',
  25 => '中插广告',
  26 => '后插广告',
  27 => 'ad.qq.com',
  28 => 'adnet',
  29 => 'adnxs',
  30 => 'adserver',
  31 => 'adsrv',
  32 => 'adsame',
  33 => 'adwo',
  34 => 'adview',
  35 => 'admob',
  36 => 'admob',
  37 => 'inmobi',
  38 => 'appodeal',
  39 => 'mopub',
  40 => 'unityads',
  41 => 'vungle',
  42 => 'applovin',
  43 => 'chartboost',
  44 => 'ironsrc',
  45 => 'mintegral',
  46 => '穿山甲',
  47 => '广点通',
  48 => '百青藤',
  49 => '芒果广告',
  50 => '优酷广告',
  51 => '腾讯广告',
  52 => 'adcdn',
  53 => 'adpush',
  54 => 'adp',
  55 => 'adstatic',
  56 => 'adcdn',
  57 => 'adapi',
  58 => 'adfile',
  59 => 'adimg',
  60 => 'adpic',
  61 => 'adpicx',
  62 => 'adv.',
  63 => 'adv-',
  64 => '-adv',
  65 => '/adv/',
  66 => 'ads/',
  67 => 'click',
  68 => 'clicktrack',
  69 => 'clickid',
  70 => 'clickTAG',
  71 => 'track',
  72 => 'tracking',
  73 => 'tracker',
  74 => 'analytics',
  75 => 'stat.',
  76 => 'tongji',
  77 => 'cnzz',
  78 => 'baidu',
  79 => 'hm.baidu',
  80 => 'hm.js',
  81 => '51.la',
  82 => 'metric',
  83 => 'pixel',
  84 => 'beacon',
  85 => 'tvod',
  86 => 'txvideo_ad',
  87 => 'aliyun_ad',
  88 => 'qiyi_ad',
  89 => 'youku_ad',
  90 => 'vip.live.com',
  91 => 'vip video',
  92 => 'vip.ad',
  93 => 'vipad',
  94 => 'playerad',
  95 => 'player_ad',
  96 => 'preroll',
  97 => 'postroll',
  98 => 'midroll',
  99 => 'videoad',
  100 => 'video_ad',
  101 => 'clipad',
  102 => 'clip_ad',
  103 => 'mp4ad',
  104 => 'ad.mp4',
  105 => 'ad.m3u8',
  106 => 'ad_',
  107 => 'promo',
  108 => 'promotion',
  109 => 'sponsor',
  110 => 'sponsored',
  111 => 'featured',
  112 => 'recommend_ad',
  113 => 'hotspot',
  114 => 'hot_ad',
  115 => 'banner',
  116 => 'bannerad',
  117 => 'floatad',
  118 => 'float_ad',
  119 => 'logo',
  120 => 'overlay',
  121 => 'overlay_ad',
  122 => 'watermark_ad',
  123 => 'skip',
  124 => 'skipad',
  125 => 'skip_ad',
  126 => 'jumpad',
  127 => 'countdown',
  128 => 'countdown_ad',
  129 => 'adcountdown',
  130 => 'logo_',
  131 => '_logo',
  132 => 'logo.',
  133 => 'corner_ad',
  134 => 'preroll_',
  135 => '_preroll',
  136 => 'postroll_',
  137 => '_postroll',
  138 => 'short_',
  139 => '_short',
  140 => 'teaser',
  141 => 'teaser_ad',
  142 => 'trailer_ad',
  143 => '_trailer',
  144 => 'intro_ad',
  145 => 'outro_ad',
  146 => 'bumper',
  147 => 'bumper_ad',
  148 => 'commercial',
  149 => 'commercials',
  150 => 'ad_content',
  151 => 'ad_clip',
  152 => 'adsegment',
  153 => 'ad_seg',
  154 => 'adv_seg',
  155 => 'adpiece',
  156 => 'breakpoint',
  157 => 'ad_break',
  158 => 'adblock',
  159 => 'block_ad',
  160 => 'noncontent',
  161 => 'non_content',
  162 => 'placeholder_ad',
),
    'whitelist_keywords' => array (
  0 => 'main',
  1 => 'content',
  2 => 'video',
  3 => '正片',
  4 => '正集',
  5 => '正片高清',
  6 => 'movie',
  7 => 'film',
  8 => 'episode',
  9 => 'ep',
  10 => 'clip',
  11 => 'clips',
  12 => 'part',
  13 => 'chapter',
  14 => 'segment',
  15 => 'seg',
  16 => 'trailer',
  17 => '预告',
  18 => 'preview',
  19 => 'preview',
  20 => 'opening',
  21 => 'op',
  22 => 'ending',
  23 => 'ed',
  24 => '片头',
  25 => '片尾',
  26 => 'hd',
  27 => 'fhd',
  28 => '4k',
  29 => 'uhd',
  30 => '1080',
  31 => '1080p',
  32 => '720',
  33 => '720p',
  34 => '540',
  35 => '480',
  36 => '360',
  37 => 'br',
  38 => 'bitrate',
  39 => 'h264',
  40 => 'h265',
  41 => 'hevc',
  42 => 'avc',
  43 => 'av1',
  44 => 'audio',
  45 => 'audio_',
  46 => '_audio',
  47 => 'aac',
  48 => 'mp3',
  49 => 'subtitle',
  50 => 'subtitle_',
  51 => '_subtitle',
  52 => 'subtitle',
  53 => 'caption',
  54 => 'caption_',
  55 => 'chn',
  56 => 'cn',
  57 => 'eng',
  58 => 'zho',
  59 => 'playlist',
  60 => 'index',
  61 => 'master',
  62 => 'variant',
  63 => 'chunklist',
  64 => 'seg',
  65 => 'segment',
  66 => 'stream',
  67 => 'live',
  68 => 'vod',
  69 => 'll-hls',
  70 => 'dvr',
  71 => 'aliyun',
  72 => 'aliyuncs',
  73 => 'alibaba',
  74 => 'alibabacdn',
  75 => 'tencent',
  76 => 'cdntc',
  77 => 'myqcloud',
  78 => 'qcloud',
  79 => 'bytedance',
  80 => 'bytedns',
  81 => 'bdydns',
  82 => 'bytecdn',
  83 => 'kuaishou',
  84 => 'ksurl',
  85 => 'kscdn',
  86 => 'bilibili',
  87 => 'bili',
  88 => 'hdslb',
  89 => 'iQiyi',
  90 => 'iqiyi',
  91 => 'qiyi',
  92 => 'youku',
  93 => 'ykimg',
  94 => 'img',
  95 => 'ykcdn',
  96 => 'mgtv',
  97 => 'hunantv',
  98 => 'imgv',
  99 => 'sohu',
  100 => 'sohuv',
  101 => 'vms',
  102 => 'letv',
  103 => 'lespark',
  104 => 'lescdn',
  105 => 'migu',
  106 => 'cmcc',
  107 => 'cmvod',
  108 => 'pps',
  109 => 'pptv',
  110 => 'pplive',
  111 => 'wasu',
  112 => 'wasucloud',
  113 => 'xunlei',
  114 => 'xlwebcloud',
  115 => 'baiducloud',
  116 => 'bcehost',
  117 => 'stream',
  118 => 'live',
  119 => 'onair',
  120 => 'on_air',
  121 => 'source',
  122 => 'src',
  123 => 'origin',
),
    'resource_types' => array (
  1 => 
  array (
    'key' => 'movie',
    'name' => '🎬 电影资源',
    'icon' => '🎬',
  ),
  2 => 
  array (
    'key' => 'tv',
    'name' => '📺 电视剧集',
    'icon' => '📺',
  ),
  3 => 
  array (
    'key' => 'variety',
    'name' => '🎤 综艺娱乐',
    'icon' => '🎤',
  ),
  4 => 
  array (
    'key' => 'anime',
    'name' => '🎭 动漫动画',
    'icon' => '🎭',
  ),
  5 => 
  array (
    'key' => 'document',
    'name' => '📚 纪录片',
    'icon' => '📚',
  ),
  6 => 
  array (
    'key' => 'sports',
    'name' => '⚽ 体育赛事',
    'icon' => '⚽',
  ),
  7 => 
  array (
    'key' => 'short',
    'name' => '📱 短视频',
    'icon' => '📱',
  ),
),
    'default_sources' => array (
  0 => 
  array (
    'name' => 'Noad-主源',
    'url' => 'https://jx.playerjy.com/?url={url}',
    'timeout' => 8,
    'type' => 1,
  ),
  1 => 
  array (
    'name' => 'Noad-备源1',
    'url' => 'https://www.yemu.xyz/?url={url}',
    'timeout' => 8,
    'type' => 1,
  ),
  2 => 
  array (
    'name' => 'Noad-备源2',
    'url' => 'https://jx.xmflv.com/?url={url}',
    'timeout' => 8,
    'type' => 2,
  ),
  3 => 
  array (
    'name' => 'Noad-备源3',
    'url' => 'https://jx.aidouer.net/?url={url}',
    'timeout' => 10,
    'type' => 2,
  ),
),
    'resource_sites' => array (
  0 => 
  array (
    'name' => '电影天堂',
    'short_code' => 'dytt',
    'base_url' => 'https://www.dytt8.com',
    'patterns' => 
    array (
      0 => 'dytt',
      1 => '电影天堂',
      2 => 'dy8',
      3 => 'dianyingtiantang',
    ),
    'algorithms' => 
    array (
      0 => 'suanfasmall',
      1 => 'suanfa3',
      2 => 'suanfadyt',
    ),
    'priority' => 1,
    'enabled' => true,
  ),
  1 => 
  array (
    'name' => '西瓜资源',
    'short_code' => 'xg',
    'base_url' => 'https://www.360kan.com',
    'patterns' => 
    array (
      0 => 'xigua',
      1 => 'xiguang',
      2 => '西瓜',
      3 => '360kan',
      4 => 'ixigua',
      5 => 'ixg',
    ),
    'algorithms' => 
    array (
      0 => 'suanfaxiguang',
      1 => 'suanfa5',
      2 => 'suanfa9',
    ),
    'priority' => 2,
    'enabled' => true,
  ),
  2 => 
  array (
    'name' => '如意资源',
    'short_code' => 'ry',
    'base_url' => 'https://jx.ruyi.com',
    'patterns' => 
    array (
      0 => 'ruyi',
      1 => '如意',
      2 => 'ry.jx',
      3 => 'ryplayer',
    ),
    'algorithms' => 
    array (
      0 => 'suanfa8',
      1 => 'suanfa4',
      2 => 'suanfa5',
    ),
    'priority' => 3,
    'enabled' => true,
  ),
  3 => 
  array (
    'name' => '爱奇艺去广告',
    'short_code' => 'iqiyi',
    'base_url' => 'https://www.iqiyi.com',
    'patterns' => 
    array (
      0 => 'iqiyi',
      1 => '爱奇艺',
      2 => 'qiyi',
    ),
    'algorithms' => 
    array (
      0 => 'suanfa9',
      1 => 'suanfa5',
      2 => 'suanfa4',
    ),
    'priority' => 5,
    'enabled' => true,
  ),
  4 => 
  array (
    'name' => '腾讯视频去广告',
    'short_code' => 'qq',
    'base_url' => 'https://v.qq.com',
    'patterns' => 
    array (
      0 => 'qq.com',
      1 => '腾讯',
      2 => 'v.qq',
      3 => 'video.qq',
    ),
    'algorithms' => 
    array (
      0 => 'suanfa7',
      1 => 'suanfa4',
      2 => 'suanfa5',
      3 => 'suanfa1',
    ),
    'priority' => 5,
    'enabled' => true,
  ),
  5 => 
  array (
    'name' => '优酷去广告',
    'short_code' => 'youku',
    'base_url' => 'https://www.youku.com',
    'patterns' => 
    array (
      0 => 'youku',
      1 => '优酷',
      2 => 'yk',
      3 => 'v.youku',
    ),
    'algorithms' => 
    array (
      0 => 'suanfa7',
      1 => 'suanfa4',
      2 => 'suanfa5',
      3 => 'suanfa1',
    ),
    'priority' => 5,
    'enabled' => true,
  ),
  6 => 
  array (
    'name' => '芒果 TV',
    'short_code' => 'mgtv',
    'base_url' => 'https://www.mgtv.com',
    'patterns' => 
    array (
      0 => 'mgtv',
      1 => '芒果',
      2 => 'hunantv',
      3 => 'mgtv.com',
    ),
    'algorithms' => 
    array (
      0 => 'suanfa7',
      1 => 'suanfa4',
      2 => 'suanfa5',
    ),
    'priority' => 6,
    'enabled' => true,
  ),
),
    'stats_enabled' => false,
    'stats_log_request' => true,
    'stats_top_limit' => 20,
    'sqlite_path' => __DIR__ . '/../cache/noad.db',
    // ========= 如意去广告算法（Ruyi Pattern Cleaner v2.1） =========
    // 算法开关：true=启用 false=关闭（关闭后完全跳过如意算法，仅使用其他广告过滤）
    'ruyi_enabled' => false,
    // Score 阈值：分数 >=此值的片段簇被视为广告。推荐值：3=保守, 4=平衡(默认), 5=激进
    'ruyi_score_threshold' => 4,
    // 基准片段时长（秒）：资源站标准视频片段时长。其他时长被视为候选广告片段
    'ruyi_baseline_sec' => 4,
    // 基准容差（秒）：基准 ±此值范围内都视为正常视频片段。默认 0.10
    'ruyi_baseline_tolerance' => 0.1,
    // 广告簇最小长度：连续非基准时长片段数量 >=此值才视为候选广告（太短=可能是正常场景切换）
    'ruyi_min_cluster_len' => 3,
    // 广告簇最大长度：超过此长度视为正常内容（如纪录片的复杂片段），默认 15
    'ruyi_max_cluster_len' => 15,
    // 广告簇最小总时长（秒）：片段组总时长 >=此值才是完整广告块，默认 15
    'ruyi_min_cluster_sum' => 15,
    // 广告簇最大总时长（秒）：超过此值的长片段组=正片内容，默认 35
    'ruyi_max_cluster_sum' => 35,
    // 短片段阈值（秒）：片段时长 <此值视为广告强信号，默认 3.0
    'ruyi_short_seg_threshold' => 3,
    // 极短片段阈值（秒）：片段时长 <此值 =直接删除（广告过渡/收尾标志），默认 1.5
    'ruyi_very_short_threshold' => 1.5,
    // DISCONTINUITY 信号：启用 M3U8 中编码断层标记（典型为广告插入点）辅助判断
    'ruyi_enable_discontinuity' => false,
    // 每天自动检测优化：每天指定时间，系统自动用示例视频测试并调整参数
    'ruyi_auto_optimize_enabled' => false,
    // 自动检测执行时间（0~23 小时），推荐凌晨 3 点，默认 3
    'ruyi_auto_optimize_hour' => 3,
    // 自动检测间隔（小时），24=每天一次，12=12小时一次，默认 24
    'ruyi_auto_optimize_interval_hours' => 24,
    // 自动检测示例视频 URL（为空时随机选择解析源），可填写经常观看的视频地址
    'ruyi_auto_optimize_sample_url' => '',
    // 调试模式：true =在 M3U8 中加入调试标记（开发专用），默认 false
    'ruyi_debug_mode' => false,
    // ========================================================
    // ===== MD5 指纹去广告参数（万能规则1） =================
    'md5_enabled' => true,
    'md5_repeat_threshold' => 3,
    'md5_max_concurrency' => 12,
    'md5_num_processes' => 8,
    'md5_segment_timeout' => 15,
    'md5_total_timeout' => 60,
    'md5_max_segment_kb' => 5000,
    'md5_use_proxy' => true,
    'md5_min_interval_ms' => 100,
    'md5_auto_learn' => true,
    'md5_auto_sync_signatures' => true,
    'md5_db_cleanup_days' => 14,
    'md5_debug' => true,
    'cache_ttl_seconds' => 1800,
    // ========================================================
    // ===== 批量解析特征学习参数（万能规则2） =================
    'feat_enabled' => true,
    'feat_max_sources' => 3,
    'feat_source_timeout' => 15,
    'feat_total_timeout' => 60,
    'feat_min_votes' => 2,
    'feat_low_resource_mode' => true,
    'feat_max_concurrency' => 2,
    'feat_sample_count' => 15,
    'feat_learn_enabled' => true,
    'feat_use_proxy' => true,
    'feat_debug' => false,
);
